### ISSUE TITLE
PrusaSlicer has encountered an error. (PrusaSlicer-2.6.1)

### ISSUE THREAD

**Issue by ArtemShevtsov** [Giadej/PrusaSlicer-Thumbnails-Ender3V2S1#2]
Hello, using CreateHeaderAndThumbnail.exe, when I store .gcode file and image starts generating, I got an error from slicer:
```
Post-processing script D:\Printing\SOFT\CreateHeaderAndThumbnail.exe on file C:\Users\ASHEVT~1\AppData\Local\Temp\.5376.gcode.pp failed.
Error code: 1
```

![image](https://github.com/Giadej/PrusaSlicer-Thumbnails-Ender3V2S1/assets/14996136/8a176dcd-5b8c-4d40-a541-790e26611541)
Here is the result of running it from the console:
![image](https://github.com/Giadej/PrusaSlicer-Thumbnails-Ender3V2S1/assets/14996136/6a2601de-fda6-4685-8f8e-c750c64d69b3)
```
Traceback (most recent call last):
  File "CreateHeaderAndThumbnail.py", line 35, in <module>
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 24466536: character maps to <undefined>
[63336] Failed to execute script 'CreateHeaderAndThumbnail' due to unhandled exception!
```

![image](https://github.com/Giadej/PrusaSlicer-Thumbnails-Ender3V2S1/assets/14996136/fae8e536-bbbc-4fa2-8549-0a775fdaebc2)

tried different sizes: 180x180 or 200x200 or 230x180 - result the same

**Comment by ArtemShevtsov** [comment]
@Giadej Maybe you can suggest something to solve this issue?
